### ISSUE TITLE
Deploy Rakudist to community infrastructure 

### ISSUE THREAD

**Issue by melezhik** [melezhik/RakuDist#3]
Upon what we've already established with @rba:

1. _Frontend_  hosted on AWS - we already have an instance - i-088204c3758429047   in Oregon region. @rba promissed to help with a domain name **rakudist.raku.org**

Consists of:

* [RakuDist](https://github.com/melezhik/RakuDist) Web UI - frontend where user runs tests using web form. RakuDist accepts user request and trigger remote Sparky builds by coping trigger files to **brezeleisen** over `scp`, this is very simple process and does not take a lot of time, so could be done over RakuDist web UI. 

*  [Sparky](https://github.com/melezhik/sparky) Web UI  - Sparky daemon web UI, used to read test reports and _maybe_ run some maintenance jobs on Sparky daemon (using the same `scp` triggering method as in RakuDist ). Sparky reports fetched from **brezeleisen** using scp (rsync?) in background mode. 

* MySQL dababase (could be [replaced](https://github.com/melezhik/sparky#running-under-other-databases-engines-mysql-postgresql) by postgrsql) - contains Sparky builds data. MySQL database should be accessible from **brezeleisen** and frontend.

2. Worker hosted on **brezeleisen** VM, consists of two components:

* Sparky daemon - queue dispatcher.  Received requests from RauDist  via `scp`  and runs tests on docker containers using `podman exec`

**Comment by melezhik** [comment]
сс @AlexDaniel

**Comment by melezhik** [comment]
The design to start with - https://github.com/melezhik/RakuDist/blob/master/Infrastructure.md

We could have 2 sparky instances, one - just to read reports, and another to run jobs on docker containers ...

@rba is it ok to rsync a relatively small amounts of files from brezeleisen  every say 5 minutes? this will require when we do sparky synchronization between aws host and  brezeleisen.

**Comment by melezhik** [comment]
After some consideration, I found a suggested design too complicated,  @rba what if we utilize ssh tunneling? see [design version 2](https://github.com/melezhik/RakuDist/blob/master/Infrastructure2.md)

**Comment by melezhik** [comment]
@rba I can't ssh from *aws* host to brezeleisen host. Looks like no routing or firewall ?

**Comment by rba** [comment]
This should work with the keys. Either on default port on on port 2222.

**Comment by melezhik** [comment]
hi @rba , I copied my private key (`id_rsa`) to aws host and this command just hangs, when I try to ssh from aws host

`ssh -i id_rsa rakudist@brezeleisen.<hidden>`

**Comment by melezhik** [comment]
implemented as defined here - https://github.com/melezhik/RakuDist/blob/master/Infrastructure2.md
